server:
  port: 8080
#Credentials are defined per microservice
spring:
  datasource:
    schema: classpath*:db/mysql/schema.sql
    data: classpath*:db/mysql/data.sql
    platform: mysql
    initialization-mode: always
  cloud:
    services:
      registrationMethod: direct

management:
  metrics:
    export:
      wavefront:
        uri: http://wavefront-proxy.service.internal:2878

wavefront:
  application:
    name: spring-petclinic-cloud
  freemium-account: false
